attention_head_size: 6
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id__cell_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        C01: 0
        C03: 1
        C05: 2
        C07: 3
        C09: 4
        C11: 5
        C13: 6
        C15: 7
        C17: 8
        C21: 9
        C25: 10
        C27: 11
        C29: 12
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 13
        - !!python/object/apply:numpy.dtype
          args:
          - U3
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 12
          - 4
          - 8
        - false
        - !!binary |
          QwAAADAAAAAxAAAAQwAAADAAAAAzAAAAQwAAADAAAAA1AAAAQwAAADAAAAA3AAAAQwAAADAAAAA5
          AAAAQwAAADEAAAAxAAAAQwAAADEAAAAzAAAAQwAAADEAAAA1AAAAQwAAADEAAAA3AAAAQwAAADIA
          AAAxAAAAQwAAADIAAAA1AAAAQwAAADIAAAA3AAAAQwAAADIAAAA5AAAA
      warn: true
  constant_fill_strategy: null
  group_ids:
  - cell_id
  lags: null
  max_encoder_length: 36
  max_prediction_length: 6
  min_encoder_length: 36
  min_prediction_idx: 0
  min_prediction_length: 6
  predict_mode: false
  randomize_length: null
  scalers:
    Current[A]: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - Current[A]
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          Huq7whGJwT8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - &id004 !!python/object/apply:numpy.dtype
        args:
        - i8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        4b0AAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          6sZpHt8l8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          Cpfn4BdM8D8=
      with_mean: true
      with_std: true
    "Temperature[\xB0C]": !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - "Temperature[\xB0C]"
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          Qh5HwVDqyD8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id004
      - !!binary |
        4b0AAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          NLuW8O/a4z8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          wjnQs62j2D8=
      with_mean: true
      with_std: true
    Voltage[V]: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - Voltage[V]
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          eHTang7fwL8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id004
      - !!binary |
        4b0AAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          9DpkYHE49T8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          KjzNufAk/D8=
      with_mean: true
      with_std: true
  static_categoricals: null
  static_reals: null
  target: SOH_ZHU
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDQAAADE2NDA1MzA5MTc5MzZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAxNjQw
        NTMwOTE3OTM2cQFhLgEAAAAAAAAAZS99Pw==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    max_length: null
    method: standard
    method_kwargs: {}
    scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDQAAADE2NDA1MzA5MTgwMzJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAxNjQw
        NTMwOTE4MDMycQFhLgEAAAAAAAAACZWEOQ==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    transformation: relu
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - Current[A]
  - Voltage[V]
  - "Temperature[\xB0C]"
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals: []
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 1.0e-05
log_gradient_flow: false
log_interval: -1
log_val_interval: -1
lstm_layers: 1
max_encoder_length: 36
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 1
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- Current[A]
- Voltage[V]
- "Temperature[\xB0C]"
time_varying_reals_encoder:
- Current[A]
- Voltage[V]
- "Temperature[\xB0C]"
weight_decay: 0.0
x_categoricals: []
x_reals:
- Current[A]
- Voltage[V]
- "Temperature[\xB0C]"
